create table t(a UInt64, b UInt64) engine=MergeTree order by a settings index_granularity=1;
system stop merges t;
insert into t select number, number from numbers_mt(50);

set enable_memory_bound_merging_of_aggregation_results = 1;
set group_by_two_level_threshold = 5;
set max_bytes_before_external_group_by = 10;
set max_threads = 4;
set optimize_aggregation_in_order = 0;
set prefer_localhost_replica = 1;
set max_block_size = 1;

set distributed_aggregation_memory_efficient = 1;

-- slightly different transforms will be generated by reading steps if we let settings randomisation to change this setting value --
set read_in_order_two_level_merge_threshold = 1000;

select throwIf(count() != 2) from remote(test_cluster_two_shards, currentDatabase(), t) group by a format Null;

